### ISSUE TITLE
ruby error , cannot load such file

### ISSUE THREAD

**Issue by ronalddas** [ahmednasir91/eb-tail#1]
~/Documents/eb-tail/bin$ ./eb-tail LowCost-env
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- eb-tail (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./eb-tail:2:in `<main>'

Any idea, why this is happening

**Comment by ahmednasir91** [comment]
@ronalddas are you trying master or the release v0.1?

**Comment by ronalddas** [comment]
@ahmednasir91  I am in master branch

**Comment by ahmednasir91** [comment]
@ronalddas try the release, it should work.
